### ISSUE TITLE
CFG interface to directly iterate over the IL

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/bil-to-boogie-translator#135]
Currently it is difficult/inefficient to use the static analysis results since there is not a strong correspondence between the IL and the CFG. To fix this we need a way of addressing IL nodes and mapping them to CFG nodes. Ideally we want to avoid having two representations of the control flow which necessitates constantly re-creating the CFG after modifying the IL. We might be able to do this by implementing the CFG as just an iterator over the IL. This iterator would have to maintain calling context and provide a succ/pred operation that closely matches TIP's. 

1. efficient way of addressing a specific block element in the IL which is stable under modifications to the block (e.g. insertion or deletion of statements and jumps to the block.)
2. Iterator over the IL Program which closely matches the interface of the TIP cfg.

**Comment by l-kent** [comment]
Once #134 is done then the program control flow can be greatly simplified, with edges only existing between blocks instead of between individual statements. Then, each block will only have a sequence of statements which can be iterated over, a single jump (which can have multiple destinations) that follows those statements. This will make it easier to implement a method of iterating over them, though the structure of the analyses may need modification.
